### PR TITLE
[rstudio] Increase the initial delay on both the livenessProbe and

### PR DESCRIPTION
**Pull request by damacus**
readinessProbe

### CODE REVIEW

**Comment by damacus** [comment]
It's seems so on the platform. I'm giving it a wide birth for now. It actually starts up almost instantly locally. But I assume there's some chown'ing going on in the background that is causing it.

**Comment by andylightfoot** [comment]
> It's seems so on the platform. I'm giving it a wide birth for now. It actually starts up almost instantly locally. But I assume there's some chown'ing going on in the background that is causing it.

OK I think we need to investigate what is causing this as it isn't really ideal to increase this timing as it means that every time R Studio starts we are adding additional time before the probes actually start checking if it is ready and then also additional time for the probe to mark it as ready. 

Maybe edit the settings in the deployment for now rather than changing the values in the helm chart?

**Review by ntoll — APPROVED** [review]
LGTM

**Comment by andylightfoot** [comment]
> > It's seems so on the platform. I'm giving it a wide birth for now. It actually starts up almost instantly locally. But I assume there's some chown'ing going on in the background that is causing it.
> 
> OK I think we need to investigate what is causing this as it isn't really ideal to increase this timing as it means that every time R Studio starts we are adding additional time before the probes actually start checking if it is ready and then also additional time for the probe to mark it as ready.
> 
> Maybe edit the settings in the deployment for now rather than changing the values in the helm chart?

erm why has this been merged?

**Comment by damacus** [comment]
I was debugging this with @ladyrassilon & @ntoll and the low timeout of 5 seconds made kubernetes restart the container multiple times before the probe got lucky and succeeded. 

30 seconds seems like a reasonably low initial delay and that's worked in testing with @ntoll and my deployments 👍🏼

**Pull request merged**
