### PR TITLE
Update jupyter-lab chart

### PR DESCRIPTION
**Pull request by calumabarnett**
Update the jupyter-lab chart for the deployment of the oracle-datascience-notebook image.

### CODE REVIEW

**Comment by calumabarnett** [comment]
@damacus some changes need to be made to the Jupyter helm chart in order to deploy the oracle-datascience-notebook image. The team suggested you may have a view on how best to document this. At the moment it's just sat in this PR but I'm not sure this is the best place!

**Comment by damacus** [comment]
I think we need a completely different helm chart for the Oracle DataScience Notebook. It might be worth having a meeting between our two teams this week?

**Comment by damacus** [comment]
Closing as @samtazzyman & Alex are discussing the future of the Oracle datascience notebook.

**Comment by damacus** [comment]
Closing as @samtazzyman & Alex are discussing the future of the Oracle Data Science notebook. And I'm fairly sure this isn't the right way forward.

**Pull request closed without merging**
